"""Generate all 7 production Jupyter Notebooks for interactive exploration."""
from pathlib import Path

import nbformat as nbf

NOTEBOOKS_DIR = Path("notebooks")
NOTEBOOKS_DIR.mkdir(parents=True, exist_ok=True)

KERNEL_METADATA = {
    "kernelspec": {
        "name": "amazon-ml",
        "display_name": "Python (amazon-ml)",
        "language": "python",
    },
    "language_info": {
        "name": "python",
        "version": "3.12.13",
        "mimetype": "text/x-python",
        "codemirror_mode": {"name": "ipython", "version": 3},
        "pygments_lexer": "ipython3",
        "nbconvert_exporter": "python",
        "file_extension": ".py",
    },
}


def create_nb_01():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 📊 01. Exploratory Data Analysis & Inspection
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

This notebook inspects the raw dataset across **Source 1** (reference), **Source 2**, **Source 3**, and the **Ground Truth** match annotations.
Key goals:
1. Examine record counts, schemas, and missing value rates.
2. Characterize the **Ground Truth**: match multiplicity and **singleton distribution** (5.58% singletons).
3. Detect cross-dataset domain shifts (e.g. open-set country discovery in Test set)."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
import numpy as np
from src.utils.io import load_config
from src.data.loader import load_tsv_records

cfg = load_config(PROJECT_ROOT / "config.yaml")
print(f"Project Root: {PROJECT_ROOT}")
print(f"Data Dir: {cfg['paths']['raw_train_dir']}")"""),
        nbf.v4.new_markdown_cell("""## 1. Load Raw Training Samples
Inspect the first 5 records from each source table."""),
        nbf.v4.new_code_cell("""raw_train_dir = PROJECT_ROOT / cfg["paths"]["raw_train_dir"]
s1_sample = load_tsv_records(raw_train_dir / "train_source1.tsv", nrows=5)
s2_sample = load_tsv_records(raw_train_dir / "train_source2.tsv", nrows=5)
s3_sample = load_tsv_records(raw_train_dir / "train_source3.tsv", nrows=5)
gt_sample = load_tsv_records(raw_train_dir / "train_ground_truth.tsv", nrows=5)

print("--- Source 1 Sample (Reference) ---")
display(s1_sample)

print("--- Ground Truth Sample ---")
display(gt_sample)"""),
        nbf.v4.new_markdown_cell("""## 2. Inspect Dataset Summary Statistics & Profiling Report
Load the precomputed profiling metrics generated by the inspection pipeline."""),
        nbf.v4.new_code_cell("""import json

report_path = PROJECT_ROOT / "artifacts" / "reports" / "data_inspection_report.json"
if report_path.exists():
    with open(report_path, encoding="utf-8") as f:
        profile = json.load(f)
    print(f"Inspected at: {profile.get('inspected_at')}")
    summary_df = pd.DataFrame(profile["datasets"]).T
    display(summary_df[["row_count", "column_count", "file_size_mb"]])
else:
    print("Run `scripts/01_inspect_data.py` to generate the complete profiling report.")"""),
        nbf.v4.new_markdown_cell("""## 3. Ground Truth Structure: Matches & Singletons
In this challenge:
- **Singletons** have `matched_entity_ids == ""` (no matching record in S2/S3).
- True matches have comma-separated entity IDs from S2 and/or S3."""),
        nbf.v4.new_code_cell("""gt_head = load_tsv_records(raw_train_dir / "train_ground_truth.tsv", nrows=50000)
gt_head["is_singleton"] = gt_head["matched_entity_ids"].str.strip() == ""
singleton_rate = gt_head["is_singleton"].mean()

print(f"Sample size: {len(gt_head):,}")
print(f"Singleton count: {gt_head['is_singleton'].sum():,} ({singleton_rate:.2%})")
print(f"Entities with matches: {(~gt_head['is_singleton']).sum():,} ({1-singleton_rate:.2%})")"""),
        nbf.v4.new_markdown_cell("""## 4. Open-Set Country Discovery
Training data contains only `US` and `IN`. In test data, **France (`FR`)** appears in ~15% of records!"""),
        nbf.v4.new_code_cell("""interim_dir = PROJECT_ROOT / cfg["paths"]["interim_dir"]
if (interim_dir / "test_source1.parquet").exists():
    test_s1 = pd.read_parquet(interim_dir / "test_source1.parquet", columns=["country"])
    print("Test S1 Country Distribution:")
    display(test_s1["country"].value_counts(dropna=False, normalize=True).apply(lambda x: f"{x:.2%}"))"""),
    ]
    return nb


def create_nb_02():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 🧹 02. Data Cleaning & Normalization
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

In this notebook, we demonstrate the deterministic text normalization pipeline:
1. **Unicode NFKD normalization** (stripping combining diacritics / accents, e.g. `é` -> `e`).
2. **Legal Corporate Suffix Normalization & Stripping** (`Inc.`, `LLC`, `Corp`, `Limited`, `GmbH`, etc.).
3. **Address standardizations & digit extraction**.
4. **Open-set country normalization** (supporting US, IN, FR)."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
from src.preprocessing.text_normalizer import normalize_business_name, strip_accents
from src.preprocessing.address_normalizer import normalize_address, extract_address_digits
from src.preprocessing.legal_terms import strip_legal_suffixes
from src.preprocessing.country_normalizer import normalize_country"""),
        nbf.v4.new_markdown_cell("""## 1. Testing Unicode & Diacritic Normalization
Accents and combining characters must be cleanly stripped across international entities."""),
        nbf.v4.new_code_cell("""messy_names = [
    "Café de Paris S.A.R.L.",
    "Münchener Rückversicherungs-Gesellschaft AG",
    "Société Générale (France) S.A.",
    "Wal-Mart Stores, Inc. #482",
    "TATA CONSULTANCY SERVICES LIMITED",
    "St. John's Health Center & Clinic, LLC"
]

results = []
for name in messy_names:
    norm_name = normalize_business_name(name)
    clean_name = strip_legal_suffixes(norm_name)
    results.append({
        "Original": name,
        "Normalized": norm_name,
        "Legal Stripped": clean_name
    })

df_clean = pd.DataFrame(results)
display(df_clean)"""),
        nbf.v4.new_markdown_cell("""## 2. Address Normalization & Digit Extraction
Street types and abbreviations are normalized, and house/suite numbers are extracted."""),
        nbf.v4.new_code_cell("""sample_addresses = [
    "123 North Main Street, Apt. 4B, New York, NY 10001",
    "P.O. Box 789, Suite 100, San Francisco, CA",
    "Plot No. 42, Sector 18, Gurugram, Haryana 122015",
    "14 Boulevard Saint-Germain, 75005 Paris, France"
]

addr_results = []
for addr in sample_addresses:
    norm_addr = normalize_address(addr)
    digits = extract_address_digits(addr)
    addr_results.append({
        "Original Address": addr,
        "Normalized Address": norm_addr,
        "Extracted Digits": digits
    })

display(pd.DataFrame(addr_results))"""),
        nbf.v4.new_markdown_cell("""## 3. Verify Cleaned Interim Parquet Files
Check the compressed Parquet datasets prepared in `data/interim/`."""),
        nbf.v4.new_code_cell("""from src.utils.io import load_config
cfg = load_config(PROJECT_ROOT / "config.yaml")
interim_dir = PROJECT_ROOT / cfg["paths"]["interim_dir"]

for p in sorted(interim_dir.glob("*.parquet")):
    df = pd.read_parquet(p)
    print(f"File: {p.name:<28} Shape: {str(df.shape):<18} Size: {p.stat().st_size / (1024*1024):.1f} MB")"""),
    ]
    return nb


def create_nb_03():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 🔍 03. Multi-Pass Blocking & Candidate Generation
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

Matching $2.2M$ Source 1 entities against $10.3M$ Source 2 & 3 candidates requires reducing the $O(N \\times M) = 2.2 \\times 10^{13}$ pairwise space.
In this notebook:
1. Vectorized multi-pass inverted index blocking:
   - **Pass 1:** Exact Normalized Business Name
   - **Pass 2:** Clean Business Name (Legal suffix stripped)
   - **Pass 3:** 4-Character Alphanumeric Prefix Key
2. Evaluate Candidate Pair Recall & Candidate Volume against Ground Truth."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import pandas as pd
from src.utils.io import load_config

cfg = load_config(PROJECT_ROOT / "config.yaml")
report_path = PROJECT_ROOT / "artifacts" / "reports" / "candidate_generation_report.json"

if report_path.exists():
    with open(report_path, encoding="utf-8") as f:
        rep = json.load(f)
    print("Candidate Generation Metrics on Evaluation Sample:")
    print(f"  Candidate Pair Recall:      {rep['candidate_pair_recall']:.2%}")
    print(f"  Entities Fully Retrieved:   {rep['entity_full_recall']:.2%}")
    print(f"  Retrieved True Pairs:       {rep['retrieved_true_pairs']:,} / {rep['total_true_pairs']:,}")
    print(f"  Candidate Volume (Mean):    {rep['candidate_volume']['mean']:.1f}")
    print(f"  Candidate Volume (Median):  {rep['candidate_volume']['median']:.1f}")
    print(f"  Candidate Volume (P95):     {rep['candidate_volume']['p95']:.1f}")
    print(f"  Candidate Volume (Max):     {rep['candidate_volume']['max']}")
else:
    print("Candidate report not found yet. Generating sample...")"""),
        nbf.v4.new_markdown_cell("""## 1. Inspect Generated Candidate Pairs
Load a sample of generated candidate pairs with ground truth labels."""),
        nbf.v4.new_code_cell("""cand_parquet = PROJECT_ROOT / cfg["paths"]["candidates_dir"] / "train_candidates.parquet"
if cand_parquet.exists():
    df_cands = pd.read_parquet(cand_parquet)
    print(f"Total candidate pairs: {len(df_cands):,}")
    print(f"Label distribution:")
    display(df_cands["label"].value_counts(normalize=True).apply(lambda x: f"{x:.2%}"))
    print("\\nSample Positive Matches:")
    display(df_cands[df_cands["label"] == 1][["source1_business_name", "candidate_business_name", "source1_business_address", "candidate_business_address"]].head(5))
else:
    print("Candidate parquet will be displayed once generated.")"""),
    ]
    return nb


def create_nb_04():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 📐 04. Pairwise Feature Engineering & Analysis
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

This notebook inspects the engineered pairwise similarity feature matrix:
1. Exact string matches (`exact_name_match`, `exact_address_match`).
2. String distance metrics:
   - Jaro-Winkler similarity on full name and clean name
   - Levenshtein ratio on name and address
3. Token-based overlap metrics:
   - Token Sort Ratio & Token Set Ratio
   - Token Jaccard overlap on business name and address
4. Address component features:
   - Extracted digit match (house/unit numbers)
   - Digits Jaccard similarity
5. Country & missingness indicators:
   - Open-set country match flag (`country_exact_match`)
   - Null indicator flags."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
from src.utils.io import load_config

cfg = load_config(PROJECT_ROOT / "config.yaml")
feat_parquet = PROJECT_ROOT / cfg["paths"]["processed_dir"] / "train_features.parquet"

if feat_parquet.exists():
    df_feat = pd.read_parquet(feat_parquet)
    print(f"Feature matrix shape: {df_feat.shape}")
    display(df_feat.head(5))
else:
    print(f"Feature matrix not found at {feat_parquet}.")"""),
        nbf.v4.new_markdown_cell("""## 1. Feature Separation: Positive vs Negative Matches
Compare mean feature values between true matches (`label == 1`) and non-matches (`label == 0`)."""),
        nbf.v4.new_code_cell("""if feat_parquet.exists():
    feature_cols = [c for c in df_feat.columns if c not in ["source1_entity_id", "candidate_entity_id", "label"]]
    stats = df_feat.groupby("label")[feature_cols].mean().T
    stats.columns = ["Non-Match (0)", "True Match (1)"]
    stats["Difference"] = stats["True Match (1)"] - stats["Non-Match (0)"]
    display(stats.sort_values(by="Difference", ascending=False))"""),
    ]
    return nb


def create_nb_05():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 🤖 05. Model Training & Experiments
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

This notebook demonstrates the Gradient Boosting entity resolution model:
1. **Entity-Aware Split (`GroupShuffleSplit`):** All candidate pairs for any given Source 1 entity are assigned exclusively to either Train or Validation, strictly preventing cross-entity data leakage.
2. **LightGBM Classifier:** Configured for high-speed tabular ranking and probability estimation.
3. **Feature Importance:** Gain and split feature rankings."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import pandas as pd
from src.utils.io import load_config
from src.models.predict import load_matching_model

cfg = load_config(PROJECT_ROOT / "config.yaml")
models_dir = PROJECT_ROOT / cfg["paths"]["models_dir"]
model_path = models_dir / "matching_model.joblib"

if model_path.exists():
    model = load_matching_model(model_path)
    print(f"Loaded trained model: {type(model).__name__}")

    feat_path = models_dir / "feature_names.json"
    with open(feat_path, encoding="utf-8") as f:
        feats = json.load(f)
    print(f"Model uses {len(feats)} input features.")"""),
        nbf.v4.new_markdown_cell("""## 1. Feature Importance Ranking
Identify the strongest predictive signals for resolving matching entities."""),
        nbf.v4.new_code_cell("""feat_imp_path = PROJECT_ROOT / "artifacts" / "reports" / "feature_importance.csv"
if feat_imp_path.exists():
    df_imp = pd.read_csv(feat_imp_path)
    display(df_imp)
elif model_path.exists():
    from src.evaluation.feature_importance import extract_feature_importance
    df_imp = extract_feature_importance(model, feats)
    display(df_imp)"""),
    ]
    return nb


def create_nb_06():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 🎯 06. Decision Threshold Optimization
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

The challenge evaluation metric is **Macro-averaged $F_{0.5}$ per Source 1 entity**:
$$F_{0.5} = \\frac{1.25 \\times \\text{Precision} \\times \\text{Recall}}{0.25 \\times \\text{Precision} + \\text{Recall}}$$

Critical properties:
- **Precision is weighted 2× higher than Recall**: False merges are heavily penalized.
- **Singletons (no true matches):** Score $1.0$ if predicted blank `""`, and $0.0$ if any false merge is predicted.
In this notebook, we sweep the decision threshold across $[0.05, 0.95]$ to find the global $F_{0.5}$ maximum."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import pandas as pd
from src.utils.io import load_config

cfg = load_config(PROJECT_ROOT / "config.yaml")
thresh_path = PROJECT_ROOT / cfg["paths"]["thresholds_dir"] / "threshold.json"

if thresh_path.exists():
    with open(thresh_path, encoding="utf-8") as f:
        opt_res = json.load(f)
    print("Optimal Threshold Results:")
    print(f"  Best Threshold:             {opt_res['best_threshold']:.3f}")
    print(f"  Best Macro F0.5 Score:      {opt_res['best_score']:.4f}")
    print(f"  Overall Precision:          {opt_res['best_metrics'].get('overall_precision', 0):.4f}")
    print(f"  Overall Recall:             {opt_res['best_metrics'].get('overall_recall', 0):.4f}")
    print(f"  Singleton Accuracy:         {opt_res['best_metrics'].get('singletons_accuracy', 0):.4f}")"""),
        nbf.v4.new_markdown_cell("""## 1. Threshold Sweep Trajectory
Inspect how Precision, Recall, and Macro $F_{0.5}$ vary across probability thresholds."""),
        nbf.v4.new_code_cell("""if thresh_path.exists() and "sweep_history" in opt_res:
    df_sweep = pd.DataFrame(opt_res["sweep_history"])
    display(df_sweep.head(15))"""),
    ]
    return nb


def create_nb_07():
    nb = nbf.v4.new_notebook(metadata=KERNEL_METADATA)
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 📈 07. Validation Evaluation & Error Analysis
### Amazon ML Challenge 2026: Multi-Source Business Entity Resolution

This notebook evaluates the end-to-end model on the held-out validation set:
1. **Confusion Matrix Analysis** (True Positives, False Positives, False Negatives, True Negatives).
2. **Singleton Accuracy & Failure Analysis**.
3. **Error Breakdown:** False merges (high-cost) vs Missed matches.
4. **Test Set Prediction Sample Inspection**."""),
        nbf.v4.new_code_cell("""import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve() if Path("..").resolve().name == "amazon" else Path(".").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import pandas as pd
from src.utils.io import load_config

cfg = load_config(PROJECT_ROOT / "config.yaml")
val_rep_path = PROJECT_ROOT / "artifacts" / "reports" / "validation_metrics.json"

if val_rep_path.exists():
    with open(val_rep_path, encoding="utf-8") as f:
        metrics = json.load(f)
    print("Validation Evaluation Metrics:")
    for k, v in metrics.items():
        if isinstance(v, float):
            print(f"  {k:<26}: {v:.4f}")
        else:
            print(f"  {k:<26}: {v}")"""),
        nbf.v4.new_markdown_cell("""## 1. Validation Confusion Matrix Table
Display the pairwise confusion matrix."""),
        nbf.v4.new_code_cell("""if val_rep_path.exists():
    tp = metrics.get("pair_tp", 0)
    fp = metrics.get("pair_fp", 0)
    fn = metrics.get("pair_fn", 0)

    cm_df = pd.DataFrame(
        [
            {"Prediction": "Match (Positive)", "Actual True Match": f"{tp:,} (TP)", "Actual Non-Match": f"{fp:,} (FP)"},
            {"Prediction": "Non-Match (Negative)", "Actual True Match": f"{fn:,} (FN)", "Actual Non-Match": "TN (Filtered by Blocker)"},
        ]
    )
    display(cm_df)"""),
        nbf.v4.new_markdown_cell("""## 2. Test Predictions Inspection
Inspect sample predictions generated for the test set."""),
        nbf.v4.new_code_cell("""matching_tsv = PROJECT_ROOT / cfg["paths"]["final_matching_file"]
if matching_tsv.exists():
    df_sub = pd.read_csv(matching_tsv, sep="\\t", nrows=20, keep_default_na=False)
    print("Sample Submission Rows (First 20):")
    display(df_sub)"""),
    ]
    return nb


def main():
    notebooks = {
        "01_data_exploration.ipynb": create_nb_01(),
        "02_data_cleaning.ipynb": create_nb_02(),
        "03_candidate_analysis.ipynb": create_nb_03(),
        "04_feature_analysis.ipynb": create_nb_04(),
        "05_model_experiments.ipynb": create_nb_05(),
        "06_threshold_analysis.ipynb": create_nb_06(),
        "07_error_analysis.ipynb": create_nb_07(),
    }
    for filename, nb in notebooks.items():
        file_path = NOTEBOOKS_DIR / filename
        with open(file_path, "w", encoding="utf-8") as f:
            nbf.write(nb, f)
        print(f"Generated: {file_path} ({len(nb.cells)} cells)")


if __name__ == "__main__":
    main()
